A = input("Input first number : ")
B = input("Input second number : ")
print(A,"+",B,"=",int(A)+int(B))
print(A,"-",B,"=",int(A)-int(B))
print(A,"*",B,"=",int(A)*int(B))
print(A,"/",B,"=",int(A)/int(B))
